labels:
  app: "valkey"
  app.kubernetes.io/name: "valkey"

architecture: standalone

replica:
  replicaCount: 0

master:
  persistence:
    enabled: true
    size: 1Gi

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi

# Restrict access to the current namespace
networkPolicy:
  enabled: true
  allowExternal: false
  allowExternalEgress: true

auth:
  enabled: true
  existingSecret: "valkey-pass"
  existingSecretPasswordKey: "VALKEY_PASS"
