apiVersion: v2
name: graphprotocol-node
description: A Helm chart for Graph Protocol Nodes
type: application
version: 0.2.2
keywords:
  - graphprotocol
  - ethereum
home: https://thegraph.com/
sources:
  - https://github.com/graphprotocol/graph-node
maintainers:
  - email: dm3ch@dm3ch.net
    name: dm3ch (original author)
  - email: engineering@techops.services
    name: TechOps Services
appVersion: v0.36.1
