{{- if and .Values.serviceAccount.create (not (empty .Values.serviceAccount.rules)) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.serviceAccountName" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "common.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "common.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
