{{- if and .Values.serviceAccount.create (not (empty .Values.serviceAccount.rules)) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "common.serviceAccountName" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
rules:
{{ toYaml .Values.serviceAccount.rules | nindent 2 }}
{{- end }}
