{{- if and .Values.serviceMonitors.enabled .Values.service }}
{{- range .Values.serviceMonitors.monitors }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "common.fullname" . }}-{{ .name }}
  {{- if $.Values.serviceMonitors.namespace }}
  namespace: {{ $.Values.serviceMonitors.namespace }}
  {{- else }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    {{- with $.Values.serviceMonitors.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: {{ .port }}
      {{- if .path }}
      path: {{ .path }}
      {{- end }}
      {{- if .interval }}
      interval: {{ .interval }}
      {{- end }}
      {{- if .scrapeTimeout }}
      scrapeTimeout: {{ .scrapeTimeout }}
      {{- end }}
      {{- if .scheme }}
      scheme: {{ .scheme }}
      {{- end }}
      {{- with .tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" $ | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  {{- with .spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }} 
