apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "valkey.fullname" . }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "valkey.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "valkey.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: valkey
        image: {{ include "valkey.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 6379
          name: valkey
        {{- if .Values.auth.enabled }}
        env:
        - name: VALKEY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.auth.existingSecret }}
              key: {{ .Values.auth.existingSecretPasswordKey }}
        command:
        - valkey-server
        - --requirepass
        - $(VALKEY_PASSWORD)
        {{- end }}
        resources:
          {{- toYaml .Values.master.resources | nindent 10 }}
        {{- if .Values.master.persistence.enabled }}
        volumeMounts:
        - name: data
          mountPath: /data
        {{- end }}
      {{- if .Values.master.persistence.enabled }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "valkey.fullname" . }}-data
      {{- end }}
