{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "valkey.fullname" . }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "valkey.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  {{- if .Values.networkPolicy.allowExternalEgress }}
  - Egress
  {{- end }}
  ingress:
  {{- if not .Values.networkPolicy.allowExternal }}
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
  {{- else }}
  - {}
  {{- end }}
  {{- if .Values.networkPolicy.allowExternalEgress }}
  egress:
  - {}
  {{- end }}
{{- end }}
