{{- if .Values.master.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "valkey.fullname" . }}-data
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.master.persistence.size }}
  {{- if .Values.master.persistence.storageClass }}
  storageClassName: {{ .Values.master.persistence.storageClass }}
  {{- end }}
{{- end }}
