apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey.fullname" . }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
spec:
  type: {{ .Values.master.service.type }}
  ports:
  - port: {{ .Values.master.service.port }}
    targetPort: valkey
    protocol: TCP
    name: valkey
  selector:
    {{- include "valkey.selectorLabels" . | nindent 4 }}